version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root # you need to set this to your desired username
      MONGO_INITDB_ROOT_PASSWORD: example # you need to set this to your desired password

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root # this is the username you set in the previous step
      ME_CONFIG_MONGODB_ADMINPASSWORD: example # this is the password you set in the previous step
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/ # mongodb://<username>:<password>@mongo:27017/
      ME_CONFIG_BASICAUTH: false